#数据库连接设置
spring:
  datasource:
    #配置h2数据库的连接地址
    url: jdbc:h2:mem:testdb;MODE=MYSQL;IGNORECASE=FALSE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: ALWAYS